Repository redhat-openshift-ecosystem/opct, pull requests merged in 2025-03, with the labels that each got.

#151 SPLAT-2030: Update dependencies from libraries
  go.mod
  go.sum
  internal/openshift/mustgathermetrics/charts.go
Labels: kind/dependency-change, lgtm, approved

#152 SPLAT-2030: fixes: bump plugins to v0.5.2 fixing security alerts
  pkg/types.go
Labels: lgtm, approved, target-release/opct-v0.5

#149 OPCT-263: docs/dev: enhance dev guides for v0.5
  docs/devel/docs.md
Labels: kind/documentation, target-release/opct-v0.5

#153 OPCT-2030: mirror aggregator server/sonobuoy img v0.57.3
  hack/image-mirror-sonobuoy/mirror.sh
Labels: kind/dependency-change, lgtm, approved, target-release/opct-v0.5

#159 NO-JIRA: CI - added step to force kind label in a PR
  .github/workflows/pull-request.yaml
Labels: lgtm, approved, kind/cicd

#156 OPCT-263: docs/cli: review cmd adm baseline with changes from #113
  docs/opct/adm/baseline.md
Labels: kind/documentation, lgtm, approved, target-release/opct-v0.5

#157 OPCT-263: docs: added guide to run e2e manually
  docs/guides/features/running-e2e.md
Labels: kind/documentation, lgtm, approved, target-release/opct-v0.5

#154 OPCT-263: docs: review installation review guide removing etcd log
  docs/devel/byo-plugin.md
  docs/guides/cluster-validation/installation-review.md
Labels: kind/documentation, lgtm, approved, target-release/opct-v0.5

#155 OPCT-263: docs: review report documentation for v0.5 feature
  docs/devel/report.md
  docs/opct/report.md
Labels: kind/documentation, lgtm, approved, target-release/opct-v0.5

#162 NO-JIRA: documentation fixes in the changelog CD pipeline
  docs/guides/cluster-validation/installation-review.md
  hack/generate-changelog.sh
  mkdocs.yml
Labels: kind/documentation, lgtm, approved

#163 OPCT-342: fix matchExpressions to remove trailing commas
  docs/guides/cluster-validation/index.md
  pkg/run/run.go
Labels: kind/bug, lgtm, approved

#164 OPCT-346: mv cmd 'adm setup-node' to 'adm e2e-dedicated taint-node'
  pkg/cmd/adm/e2ed/root.go
  pkg/cmd/adm/e2ed/taintNode.go
  pkg/cmd/adm/root.go
  pkg/cmd/adm/setupNode.go
Labels: kind/documentation, lgtm, approved

#166 NO-JIRA: Update owners with all eng members of SPLAT
  OWNERS
Labels: kind/cleanup

#123 OPCT-304: cmd: adm parser-junit
  docs/assets/output/_generate-outputs.sh
  docs/assets/output/opct-adm-parse-junit.txt
  docs/opct/adm/parse-junit.md
  mkdocs.yml
  pkg/api/junit.go
  pkg/api/junit_test.go
  pkg/cmd/adm/parsejunit.go
  pkg/cmd/adm/root.go
Labels: kind/feature, lgtm, approved, component/CLI, target-release/opct-v0.6

#160 OPCT-332: added a controller to mutate e2e pods failed to schedule
  docs/devel/guide.md
  pkg/cmd/adm/e2ed/controller.go
  pkg/cmd/adm/e2ed/root.go
  pkg/cmd/adm/e2ed/taintNode.go
  pkg/destroy/destroy.go
  pkg/run/run.go
  pkg/types.go
Labels: kind/feature, lgtm, approved, target-release/opct-v0.6

#161 OPCT-339: cleaner: enhance archive removing unused objects
  .github/workflows/e2e.yaml
  internal/cleaner/cleaner.go
  pkg/cmd/adm/cleaner.go
  pkg/cmd/adm/parsemetrics.go
Labels: kind/feature, lgtm, approved

#167 OPCT-348: bump plugins for v0.6.0-alpha.1
  pkg/types.go
Labels: kind/dependency-change, lgtm, approved, target-release/opct-v0.6

#150 OPCT-349: docs: update instructions with valid OCP platform types for VCSP
  docs/guides/cluster-validation/index.md
Labels: kind/documentation, lgtm, approved

#165 OPCT-346: docs: rename setup-node to e2e-dedicated taint-node
  README.md
  docs/README.md
  docs/assets/output/_generate-outputs.sh
  docs/assets/output/opct-adm-e2e-dedicated-taint-node.txt
  docs/assets/output/opct-adm-setup-node.txt
  docs/assets/output/opct-run.txt
  docs/getting-started.md
  docs/guides/cluster-validation/index.md
  docs/guides/features/validating-arm-installations.md
  docs/opct/adm/e2e-dedicated-taint-node.md
  docs/opct/adm/setup-node.md
  mkdocs.yml
  pkg/run/run.go
Labels: kind/documentation, lgtm, approved, target-release/opct-v0.6
